{
  "openapi": "3.0.0",
  "info": {
    "title": "dPO API",
    "version": "1.0.0",
    "description": "dPO API with autogenerated swagger doc"
  },
  "servers": [
    {
      "url": "http://localhost:5000"
    }
  ],
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "paths": {
    "/api/v1/booking/": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": [
          "Bookings"
        ],
        "description": "Get a list of bookings for a user.",
        "parameters": [
          {
            "in": "query",
            "name": "filter",
            "schema": {
              "type": "string",
              "enum": [
                "upcoming",
                "current",
                "past"
              ]
            },
            "description": "Filter the bookings by their status."
          }
        ],
        "responses": {
          "200": {
            "description": "A list of bookings."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/booking/payments": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": [
          "Bookings"
        ],
        "description": "Initiate payment for a booking.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "bookingId": {
                    "type": "string"
                  },
                  "amount": {
                    "type": "number"
                  },
                  "currency": {
                    "type": "string"
                  },
                  "paymentMethod": {
                    "type": "string"
                  }
                },
                "example": {
                  "bookingId": "64f79d13de627ea40be7bc8b",
                  "amount": 500,
                  "currency": "gbp",
                  "paymentMethod": "pm_card_visa"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Payment initiated successfully."
          },
          "400": {
            "description": "Invalid input or other client error."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/booking/check-payment-detail": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": [
          "Bookings"
        ],
        "description": "getPaymentIntentDetails.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "string",
                "properties": {
                  "paymentIntentId": {
                    "type": "string"
                  }
                },
                "example": {
                  "paymentIntentId": "pi_3NroGcGK6Yb1Azu3151rb6mu"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Payment initiated successfully."
          },
          "400": {
            "description": "Invalid input or other client error."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/booking/get-payment-list": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": [
          "Bookings"
        ],
        "description": "listCharges.",
        "responses": {
          "201": {
            "description": "Payment initiated successfully."
          },
          "400": {
            "description": "Invalid input or other client error."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/booking/{spaceId}": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": [
          "Bookings"
        ],
        "description": "Create a new booking for a space.",
        "parameters": [
          {
            "in": "path",
            "name": "spaceId",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "ID of the space to book."
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "startDate": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "endDate": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "quantity": {
                    "type": "integer"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Booking successfully created."
          },
          "400": {
            "description": "Invalid input or other client error."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/connection/": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "List all connections",
        "tags": [
          "Connection"
        ],
        "responses": {
          "200": {
            "description": "Returns a list of all connections"
          }
        }
      }
    },
    "/api/v1/connection/send-request/{recipientId}": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Send a connection request",
        "tags": [
          "Connection"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "recipientId",
            "required": true,
            "description": "ID of the recipient user",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Connection request sent successfully"
          }
        }
      }
    },
    "/api/v1/connection/approve-request/{senderId}": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Approve a connection request",
        "tags": [
          "Connection"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "senderId",
            "required": true,
            "description": "ID of the sender user",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Connection request approved successfully"
          }
        }
      }
    },
    "/api/v1/contactus/": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Create a new contact",
        "tags": [
          "Contacts"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "email",
                  "subject",
                  "details"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "subject": {
                    "type": "string"
                  },
                  "details": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Contact created successfully"
          },
          "400": {
            "description": "Invalid request body"
          }
        }
      }
    },
    "/api/v1/contactus/{id}": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Get a single contact by ID",
        "tags": [
          "Contacts"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID of the contact to fetch",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Contact fetched successfully"
          },
          "404": {
            "description": "Contact not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/api/v1/contactus/all": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Get all contacts",
        "tags": [
          "Contacts"
        ],
        "responses": {
          "200": {
            "description": "List of all contacts"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/api/v1/feedback": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Create a feedback",
        "tags": [
          "Feedback"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "subject",
                  "details"
                ],
                "properties": {
                  "subject": {
                    "type": "string"
                  },
                  "details": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Feedback successfully created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Feedback"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/api/v1/plan/": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Get plans",
        "tags": [
          "Plan"
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      },
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Create plan",
        "tags": [
          "Plan"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "2 months",
                  "price": 18.99,
                  "interval": "month",
                  "interval_count": 1
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/plan/update-plan": {
      "patch": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Update plan",
        "tags": [
          "Plan"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "planId": "64bebe2426ba0a95e43a8d79",
                  "name": "2 months"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/plan/{planId}": {
      "delete": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Delete plan",
        "tags": [
          "Plan"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "planId",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "ID of the plan."
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/profile/{userId}/overview/header": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Retrieve the profile of the user",
        "tags": [
          "Profile"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "ID of the user."
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/profile/{userId}/overview/info": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Retrieve the profile info of the user",
        "tags": [
          "Profile"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "ID of the user."
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/profile/{userId}/renter-profile/": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Retrieve the profile info of the renter",
        "tags": [
          "Profile"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "ID of the renter."
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/review/": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "List all reviews",
        "tags": [
          "Review"
        ],
        "responses": {
          "200": {
            "description": "Returns a list of all reviews"
          }
        }
      }
    },
    "/api/v1/review/add-review/": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Add a review",
        "tags": [
          "Review"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "revieweeId": "64ee1c6598cf0925206aad75",
                  "content": "Good!"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Review added successfully"
          }
        }
      }
    },
    "/api/v1/space/": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Get spaces",
        "tags": [
          "Space"
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      },
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Add Space",
        "tags": [
          "Space"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "spaces_imgs": {
                    "type": "string",
                    "format": "binary"
                  },
                  "name": {
                    "type": "string",
                    "example": "Sample space"
                  },
                  "address": {
                    "type": "string",
                    "example": "Canada Line - SkyTrain, Metro Vancouver, BC, Canada"
                  },
                  "dayRate": {
                    "type": "integer",
                    "example": "17"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/subscription/newsletter": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Create a new subscription for newsletter",
        "tags": [
          "Subscriptions"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email"
                ],
                "properties": {
                  "email": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "subscription created successfully"
          },
          "400": {
            "description": "Invalid request body"
          }
        }
      }
    },
    "/api/v1/support/": {
      "get": {
        "tags": [
          "Support"
        ],
        "summary": "Get all support questions.",
        "responses": {
          "200": {
            "description": "A list of support questions."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      },
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": [
          "Support"
        ],
        "summary": "Add a new support question.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "tag": {
                    "type": "string"
                  },
                  "body": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Support question added successfully."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/support/tag/{tag}": {
      "get": {
        "tags": [
          "Support"
        ],
        "summary": "Get support questions by tag.",
        "parameters": [
          {
            "in": "path",
            "name": "tag",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "Tag of the support question (e.g., renters, partners, others)."
          }
        ],
        "responses": {
          "200": {
            "description": "A list of support questions."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/support/search": {
      "get": {
        "tags": [
          "Support"
        ],
        "summary": "Search support questions by title.",
        "parameters": [
          {
            "in": "query",
            "name": "title",
            "schema": {
              "type": "string"
            },
            "description": "Keyword to search in the title."
          }
        ],
        "responses": {
          "200": {
            "description": "A list of matched support questions."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/support/{id}": {
      "delete": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": [
          "Support"
        ],
        "summary": "Delete a support question by ID.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "ID of the support question to delete."
          }
        ],
        "responses": {
          "204": {
            "description": "Support question deleted successfully."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/user/logout/{userId}": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": [
          "User"
        ],
        "description": "Logout",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "ID of the user."
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/user/user-cards": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Get user cards",
        "tags": [
          "User"
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/user/register": {
      "post": {
        "summary": "Register User",
        "tags": [
          "User"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "role": "Lister",
                  "firstName": "Usama",
                  "lastName": "Bashir",
                  "email": "meetmrusama@gmail.com",
                  "password": "12345678"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/user/company-profile": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Add company profile",
        "tags": [
          "Company Profile"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "companyName": {
                    "type": "string",
                    "example": "Company"
                  },
                  "DBAName": {
                    "type": "string",
                    "example": "DBA"
                  },
                  "contactFirstName": {
                    "type": "string",
                    "example": "First Name"
                  },
                  "contactLastName": {
                    "type": "string",
                    "example": "Last Name"
                  },
                  "contactEmail": {
                    "type": "string",
                    "example": "contact@gmail.com"
                  },
                  "phoneNo": {
                    "type": "integer",
                    "example": "123456789"
                  },
                  "businessType": {
                    "type": "string",
                    "example": "Parking"
                  },
                  "FEIN": {
                    "type": "string",
                    "example": "FEIN"
                  },
                  "street": {
                    "type": "string",
                    "example": "Street"
                  },
                  "city": {
                    "type": "string",
                    "example": "City"
                  },
                  "state": {
                    "type": "string",
                    "example": "State"
                  },
                  "zipCode": {
                    "type": "string",
                    "example": "zipCode"
                  },
                  "USDOT": {
                    "type": "string",
                    "example": "USDOT"
                  },
                  "employees": {
                    "type": "integer",
                    "example": "4"
                  },
                  "drivers": {
                    "type": "integer",
                    "example": "2"
                  },
                  "company_profile": {
                    "type": "string",
                    "format": "binary"
                  },
                  "policy_doc": {
                    "type": "string",
                    "format": "binary"
                  },
                  "providerName": {
                    "type": "string",
                    "example": "providerName"
                  },
                  "providerPhone": {
                    "type": "string",
                    "example": "providerPhone"
                  },
                  "policyNumber": {
                    "type": "string",
                    "example": "policyNumber"
                  },
                  "policyStartDate": {
                    "type": "string",
                    "example": "01-08-2023"
                  },
                  "policyEndDate": {
                    "type": "string",
                    "example": "01-08-2023"
                  },
                  "policyStreetAddress": {
                    "type": "string",
                    "example": "policyStreetAddress"
                  },
                  "policyCity": {
                    "type": "string",
                    "example": "policyCity"
                  },
                  "policyState": {
                    "type": "string",
                    "example": "policyState"
                  },
                  "policyZipCode": {
                    "type": "string",
                    "example": "policyZipCode"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/user/personal-info": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Add PersonalInfo",
        "tags": [
          "Personal Info"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "gender": {
                    "type": "string",
                    "example": "Male"
                  },
                  "firstName": {
                    "type": "string",
                    "example": "Usama"
                  },
                  "lastName": {
                    "type": "string",
                    "example": "Bashir"
                  },
                  "companyTitle": {
                    "type": "string",
                    "example": "companyTitle"
                  },
                  "email": {
                    "type": "string",
                    "example": "meetmrusama@gmail.com"
                  },
                  "phone": {
                    "type": "integer",
                    "example": "123456789"
                  },
                  "language": {
                    "type": "string",
                    "example": "English"
                  },
                  "street": {
                    "type": "string",
                    "example": "street"
                  },
                  "city": {
                    "type": "string",
                    "example": "city"
                  },
                  "state": {
                    "type": "string",
                    "example": "state"
                  },
                  "zipCode": {
                    "type": "string",
                    "example": "zipCode"
                  },
                  "bio": {
                    "type": "string",
                    "example": "bio"
                  },
                  "emergencyFirstName": {
                    "type": "string",
                    "example": "emergencyFirstName"
                  },
                  "emergencyLastName": {
                    "type": "string",
                    "example": "emergencyLastName"
                  },
                  "emergencyPhone": {
                    "type": "string",
                    "example": "emergencyPhone"
                  },
                  "emergencyEmail": {
                    "type": "string",
                    "example": "asd@asd.asd"
                  },
                  "emergencyRelationship": {
                    "type": "string",
                    "example": "emergencyRelationship"
                  },
                  "emergencyLanguage": {
                    "type": "string",
                    "example": "emergencyLanguage"
                  },
                  "emergencyStreet": {
                    "type": "string",
                    "example": "emergencyStreet"
                  },
                  "emergencyCity": {
                    "type": "string",
                    "example": "emergencyCity"
                  },
                  "emergencyState": {
                    "type": "string",
                    "example": "emergencyState"
                  },
                  "emergencyZipCode": {
                    "type": "string",
                    "example": "emergencyZipCode"
                  },
                  "profile_pic": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/user/equipment": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Add equipment",
        "tags": [
          "Equipment"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "equipmentType": "equipmentType",
                  "equipmentIdentity": "equipmentIdentity",
                  "equipmentLength": "equipmentLength",
                  "equipmentUnitNo": "equipmentUnitNo",
                  "equipmentYear": "equipmentYear",
                  "equipmentMake": "equipmentMake",
                  "equipmentModel": "equipmentModel",
                  "equipmentColor": "equipmentColor",
                  "plateNo": "plateNo",
                  "plateState": "plateState",
                  "chassis": "chassis"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/user/verify-otp": {
      "post": {
        "summary": "Verify OTP",
        "tags": [
          "User"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "meetmrusama@gmail.com",
                  "otp": "895953"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/user/login": {
      "post": {
        "summary": "Login",
        "tags": [
          "User"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "meetmrusama@gmail.com",
                  "password": "12345678"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/user/add-card": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Add user card",
        "tags": [
          "User"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "cardNo": "4242424242424242",
                  "expMonth": 11,
                  "expYear": 2028,
                  "cvc": 123,
                  "name": "Usama Bashir"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/user/search-connected": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Search connected users in chat based on a query",
        "tags": [
          "User"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "query",
            "required": true,
            "description": "The search query to match against connected users' firstName, lastName, or email.",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns connected users matching the search query"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/api/v1/user/me": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Fetch details of the logged-in user",
        "tags": [
          "User"
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/api/v1/user/user-conversations": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "Get user conversations",
        "tags": [
          "User"
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    }
  },
  "tags": []
}